### ISSUE TITLE
Pregunta

### ISSUE THREAD

**Issue by cristian-programmer** [SergioHdzReyes/nCurses#1]
Este repositorio es para aprender c?, estoy afianzando mis conocimiento y pienso hacer todos los ejercicios del libro escrito por los autores ( https://www.amazon.com/Programming-Language-2nd-Brian-Kernighan/dp/0131103628), no se si habrá un espacio para alojarlo aquí, en alguna sub-carpeta.
que te parece?

**Comment by SergioHdzReyes** [comment]
Que tal cristian, claro que si lo puedes utilizar, tambien este repositorio esta enfocado a conocer mas de C pasame tu llave ssh para que puedas subir tu contenido.

**Comment by cristian-programmer** [comment]
No estoy usando llave ssh, tendre que generarla

**Comment by SergioHdzReyes** [comment]
Ya te mande la invitación.

**Comment by cristian-programmer** [comment]
gracias, mejor así.
